Adds Base app with bottom navigation bar
remunds/data-offloading-app pull request #10
Opened 2020-12-07 12:41 UTC by mxsrv

2020-12-07 14:51 UTC, remunds commented
Userstory says that swiping is supposed to be possible.

2020-12-07 14:56 UTC, remunds requested changes

2020-12-07 14:56 UTC, remunds commented on lib/main.dart
> +                      //not yet implemented
add an opening window (user story)

2020-12-14 13:58 UTC, laura-jehn commented on lib/main.dart
> +  static const String _title = 'Data Offloading App';
should be title without underscore according to the dart style guide

2020-12-14 14:04 UTC, laura-jehn requested changes
- follows style guide
- sufficient commentary
- modular, bottom navigation bar in one file, page for 'settings' in separate file
- redundancy is okay
- code fulfills its purpose
- appropriate data structures
- good variable naming

2020-12-14 14:04 UTC, laura-jehn commented on lib/main.dart
> +  BaseAppWidget({Key key}) : super(key: key); //muss ich noch herausfinden
kein sinnvolles kommentar

2020-12-14 14:11 UTC, laura-jehn approved these changes

2020-12-14 14:12 UTC, remunds approved these changes

2020-12-14 14:14 UTC, merged